name: Publish to NPM

on:
  push:
    tags:
      - "v*" # Matches tags starting with "v"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
